/* 
 * ARQUIVO DE DADOS (DATABASE) - MODELOS REAIS GT7 (COM ASSETS)
 */

const CARS = [
  {
    id: "porsche_911_rsr",
    name: "Porsche 911 RSR (991) '17",
    manufacturer: "Porsche",
    category: "Gr.3",
    drivetrain: "RR",        
    enginePos: "REAR",
    weightKg: 1243,
    weightDistFront: 38,     
    weightDistRear: 62,
    ppBase: 730,
    notes: "O rei da frenagem. O motor traseiro exige precisão na entrada de curva.",
    image: "https://i.redd.it/6i65gwkrnxde1.jpeg"
  },
  {
    id: "ferrari_458_gt3",
    name: "Ferrari 458 Italia GT3 '13",
    manufacturer: "Ferrari",
    category: "Gr.3",
    drivetrain: "MR",
    enginePos: "MID",
    weightKg: 1215,
    weightDistFront: 43,
    weightDistRear: 57,
    ppBase: 725,
    notes: "Equilíbrio perfeito. O motor V8 central oferece uma rotação natural incrível.",
    image: "https://www.gran-turismo.com/common/dist/gt7/carlist/assets/car2158_2_01-DMf6M2F3.jpg"
  },
  {
    id: "amg_gt3",
    name: "Mercedes-AMG GT3 '16",
    manufacturer: "Mercedes-Benz",
    category: "Gr.3",
    drivetrain: "FR",
    enginePos: "FRONT",
    weightKg: 1320,
    weightDistFront: 52,
    weightDistRear: 48,
    ppBase: 722,
    notes: "Poderoso V8 dianteiro. Exige cuidado com a subviragem em curvas lentas.",
    image: "https://hips.hearstapps.com/hmg-prod/amv-prod-cad-assets/images/16q1/665019/mercedes-amg-gt3-race-car-first-drive-review-car-and-driver-photo-666972-s-original.jpg"
  },
  {
    id: "subaru_wrx_gr3",
    name: "Subaru WRX Gr.3",
    manufacturer: "Subaru",
    category: "Gr.3",
    drivetrain: "4WD",
    enginePos: "FRONT",
    weightKg: 1280,
    weightDistFront: 50,
    weightDistRear: 50,
    ppBase: 718,
    notes: "Tração total. Excelente estabilidade em reaceleração, mas 'espalha' na entrada.",
    image: "https://www.gran-turismo.com/common/dist/gt7/carlist/assets/car2186_2_01-Bh95kT3O.jpg"
  },
  {
    id: "megane_gr3",
    name: "Renault Sport Mégane Gr.3",
    manufacturer: "Renault Sport",
    category: "Gr.3",
    drivetrain: "FF",
    enginePos: "FRONT",
    weightKg: 1200,
    weightDistFront: 62,
    weightDistRear: 38,
    ppBase: 710,
    notes: "Rápido em curvas técnicas. O desafio é gerenciar o desgaste dos pneus dianteiros.",
    image: "https://static.wikia.nocookie.net/gran-turismo/images/0/0b/Renault_Sport_M%C3%A9gane_Trophy_%2711.jpg/revision/latest?cb=20220906000236"
  },
  {
    id: "bmw_m6_gt3",
    name: "BMW M6 GT3 Endurance '16",
    manufacturer: "BMW",
    category: "Gr.3",
    drivetrain: "FR",
    enginePos: "FRONT",
    weightKg: 1300,
    weightDistFront: 50,
    weightDistRear: 50,
    ppBase: 724,
    notes: "Base de entre-eixos longa. Muito estável em curvas de alta velocidade.",
    image: "https://imagedelivery.net/nkaANmEhdg2ZZ4vhQHp4TQ/79764c5a-10fe-4b33-77d3-5c37abba3300/public"
  },
  {
    id: "aston_vantage_gt3",
    name: "Aston Martin Vantage V12 GT3 '12",
    manufacturer: "Aston Martin",
    category: "Gr.3",
    drivetrain: "FR",
    enginePos: "FRONT",
    weightKg: 1250,
    weightDistFront: 51,
    weightDistRear: 49,
    ppBase: 723,
    notes: "Som do V12 glorioso. Torque massivo que exige controle de tração preciso.",
    image: "https://static.wikia.nocookie.net/gran-turismo/images/9/93/Aston_Martin_V12_Vantage_GT3_%2712.jpg/revision/latest?cb=20221003125644"
  },
  {
    id: "lamborghini_huracan_gt3",
    name: "Lamborghini Huracán GT3 '15",
    manufacturer: "Lamborghini",
    category: "Gr.3",
    drivetrain: "MR",
    enginePos: "MID",
    weightKg: 1230,
    weightDistFront: 40,
    weightDistRear: 60,
    ppBase: 728,
    notes: "Agressivo e rápido. O centro de gravidade baixo permite mudanças de direção rápidas.",
    image: "https://www.lamborghini.com/sites/it-en/files/DAM/lamborghini/news/2022/05_03_lancio_gt3_evo2/cover_m.jpg"
  },
  {
    id: "mclaren_650s_gt3",
    name: "McLaren 650S GT3 '15",
    manufacturer: "McLaren",
    category: "Gr.3",
    drivetrain: "MR",
    enginePos: "MID",
    weightKg: 1240,
    weightDistFront: 42,
    weightDistRear: 58,
    ppBase: 726,
    notes: "Eficiência aerodinâmica. Excelente em pistas com curvas de raio longo.",
    image: "https://static.wikia.nocookie.net/gran-turismo/images/9/9f/McLaren_650S_GT3_%2715.jpg/revision/latest?cb=20220930185156"
  }
];

const TRACKS = [
  {
    id: "sardegna_a",
    name: "Sardegna - Road Track A",
    country: "Itália",
    downforce: "LOW",        
    surface: "SMOOTH",       
    longestStraightM: 1800,
    targetSpeed: 290,
    hasBumps: false,
    circuitType: "PERMANENT",
    description: "Pista técnica e rápida sob o sol da Sardenha.",
    image: "assets/gt7_sardegna_track_1777168856140.png"
  },
  {
    id: "le_mans",
    name: "Circuit de la Sarthe",
    country: "França",
    downforce: "LOW",
    surface: "SMOOTH",
    longestStraightM: 5900,
    targetSpeed: 340,
    hasBumps: false,
    circuitType: "PERMANENT",
    description: "A lendária reta Mulsanne exige velocidade final extrema.",
    image: "assets/gt7_lemans_track_1777168867639.png"
  },
  {
    id: "monza",
    name: "Autodromo Nazionale Monza",
    country: "Itália",
    downforce: "LOW",
    surface: "SMOOTH",
    longestStraightM: 1150,
    targetSpeed: 310,
    hasBumps: false,
    circuitType: "PERMANENT",
    description: "O Templo da Velocidade. Foco total em tração e frenagem.",
    image: "assets/gt7_monza_track_1777168883607.png"
  },
  {
    id: "nurburgring_nordschleife",
    name: "Nürburgring Nordschleife",
    country: "Alemanha",
    downforce: "HIGH",
    surface: "BUMPY",
    longestStraightM: 450,
    targetSpeed: 270,
    hasBumps: true,
    circuitType: "MIXED",
    description: "O Inferno Verde. 20km de puro desafio técnico.",
    image: "assets/gt7_nordschleife_track_1777168686856.png"
  },
  {
    id: "spa",
    name: "Circuit de Spa-Francorchamps",
    country: "Bélgica",
    downforce: "HIGH",
    surface: "MIXED",
    longestStraightM: 740,
    targetSpeed: 280,
    hasBumps: true,
    circuitType: "PERMANENT",
    description: "A mítica Eau Rouge testa a coragem de qualquer piloto.",
    image: "assets/gt7_spa_track_1777168718779.png"
  },
  {
    id: "mount_panorama",
    name: "Mount Panorama Motor Racing Circuit",
    country: "Austrália",
    downforce: "HIGH",
    surface: "MIXED",
    longestStraightM: 680,
    targetSpeed: 280,
    hasBumps: true,
    circuitType: "HILLCLIMB",
    description: "Subidas íngremes e descidas perigosas em Bathurst.",
    image: "assets/gt7_mount_panorama_track_1777168733435.png"
  },
  {
    id: "tokyo_expressway",
    name: "Tokyo Expressway - Central",
    country: "Japão",
    downforce: "MEDIUM",
    surface: "SMOOTH",
    longestStraightM: 420,
    targetSpeed: 270,
    hasBumps: false,
    circuitType: "STREET",
    description: "Corridas noturnas entre os prédios de Tóquio.",
    image: "assets/gt7_tokyo_track_1777168899661.png"
  },
  {
    id: "trial_mountain",
    name: "Trial Mountain Circuit",
    country: "Japão",
    downforce: "MEDIUM",
    surface: "MIXED",
    longestStraightM: 380,
    targetSpeed: 260,
    hasBumps: true,
    circuitType: "PERMANENT",
    description: "Um clássico do Gran Turismo renovado para a nova geração.",
    image: "assets/gt7_trial_mountain_track_1777168916667.png"
  },
  {
    id: "dragon_trail",
    name: "Dragon Trail - Seaside",
    country: "Croácia",
    downforce: "MEDIUM",
    surface: "SMOOTH",
    longestStraightM: 510,
    targetSpeed: 280,
    hasBumps: false,
    circuitType: "PERMANENT",
    description: "A 'Chicane da Morte' é o ponto alto desta pista croata.",
    image: "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&q=80&w=800"
  }
];
